# Generated by Django 5.2.5 on 2025-10-08 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBatchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Teacher Batch Student',
                'verbose_name_plural': 'Teacher Batch Students',
                'db_table': 'teacher_batch_student',
                'unique_together': {('batch', 'student')},
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_students',
            field=models.ManyToManyField(related_name='batch_memberships', through='teacher.TeacherBatchStudent', to='student.student'),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('sub_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='teacher.batch')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_uploads', to='student.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
