# Generated by Django 5.2.5 on 2025-10-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_students',
        ),
        migrations.DeleteModel(
            name='TeacherBatchStudent',
        ),
    ]
