# Generated by Django 5.2.5 on 2025-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_batch_batch_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-08 06:40:00'),
            preserve_default=True,
        ),
    ]
