# Generated by Django 5.2.5 on 2025-10-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_batch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
