# Generated by Django 5.2.5 on 2025-10-09 03:32

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_batch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='to_date',
            field=models.DateField(default=teacher.models.Upload.get_default_to_date),
        ),
    ]
