# Generated by Django 5.2.5 on 2025-10-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('Nehru nagar', 'Nehru nagar'), ('Gandhipuram', 'Gandhipuram')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
