# Generated by Django 5.2.5 on 2025-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_batchcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcode',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchcode',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
